name: Forecast Logging (2 Hour Interval)

on:
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:

      # Checkout the repository
      - name: Git checkout
        uses: actions/checkout@v3
        with: { ref: main }

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13" # Specify the Python version you need

      # Install dependencies (if required)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run main.py with secrets
      - name: Run fetch_forecast.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DATABASE_URL_DEVELOPMENT: ${{ secrets.DATABASE_URL_DEVELOPMENT }}
          DATABASE_URL_MAIN: ${{ secrets.DATABASE_URL_MAIN }}
          DATABASE_URL_TRIAL: ${{ secrets.DATABASE_URL_TRIAL }}
          DATABASE_URL_FEBRUARY_2025: ${{ secrets.DATABASE_URL_FEBRUARY_2025 }}
          DATABASE_URL_MASTER: ${{ secrets.DATABASE_URL_MASTER }}
        run: |
          python fetch_forecast.py